"""Robustness checks for the 35C charge-focus analysis.

Three independent diagnostics:

  Task A — expand all 4 reference regions per plateau individually
           (do they drift in the same direction? which is most stable?)
  Task B — replace mean-of-refs with median-of-refs and recompute
           the cell-specific Delta-end table (robustness to a single bad ref)
  Task C — tab-vs-center sub-ROI comparison, no external reference at all
           (tab-distal / interior / tab-proximal trajectories vs rest time
            per plateau; this is the handoff-recommended primary evidence
            because both bands share the same thermal and system drift)

Outputs (all under reports/longrun_cycling_35c_charge_focus/):
  taskA_individual_refs_<mod>.png
  taskC_tab_vs_center_<mod>.png
  taskC_equilibrium_subregions.png
  ROBUSTNESS.md (full numeric report; appended, never overwritten)
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.axes
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

_orig_imshow = matplotlib.axes.Axes.imshow


def _patched_imshow(self, X, *args, **kwargs):
    extent = kwargs.get("extent")
    if extent is not None and len(extent) == 4 and extent[2] > extent[3]:
        kwargs["extent"] = [extent[0], extent[1], extent[3], extent[2]]
        kwargs.setdefault("origin", "lower")
    return _orig_imshow(self, X, *args, **kwargs)


matplotlib.axes.Axes.imshow = _patched_imshow

HERE = Path(__file__).resolve().parent
PROJ = HERE.parents[1]
sys.path.insert(0, str(PROJ / "scripts" / "longrun_analysis"))
from common import NOISE_FLOOR  # noqa: E402

OUT_ROOT = PROJ / "reports" / "longrun_cycling_35c_charge_focus"
CACHE_DIR = OUT_ROOT / "_cache"
REPORT_PATH = OUT_ROOT / "ROBUSTNESS.md"

UNITS = {
    "amplitude": ("mV", 1e3, NOISE_FLOOR["amp_sigma_roi_mv"]),
    "tof":       ("ns", 1e3, NOISE_FLOOR["tof_sigma_roi_ns"]),
    "energy":    ("a.u.", 1.0, NOISE_FLOOR["energy_sigma_roi"]),
}

REST_STEPS = [5, 7, 9, 11]
SOC_LABELS = [20, 40, 60, 80]

# Tab geometry: tabs at large X (right edge in plot, per project memory).
# Same three X-bands as 25C tab analysis, intersected with ROI.
SUBREGIONS = {
    "tab-distal":   (14.0, 30.0),
    "interior":     (30.0, 50.0),
    "tab-proximal": (50.0, 64.5),
}

REFS_X = {
    "far-left":  (0.0, 10.0, 0.0, 72.0),
    "far-right": (70.0, 80.0, 0.0, 72.0),
    "far-top":   (0.0, 80.0, 0.0, 12.0),
    "far-bot":   (0.0, 80.0, 58.0, 72.0),
}


def _xy_band(roi, x_mm, y_mm, x_lo, x_hi, y_lo, y_hi, exclude_roi=True):
    cl = int(np.searchsorted(x_mm, x_lo)); ch = int(np.searchsorted(x_mm, x_hi))
    rl = int(np.searchsorted(y_mm, y_lo)); rh = int(np.searchsorted(y_mm, y_hi))
    m = np.zeros_like(roi, dtype=bool)
    m[rl:rh, cl:ch] = True
    if exclude_roi:
        m &= ~roi
    return m


def _xband_in_roi(roi, x_mm, x_lo, x_hi):
    cl = int(np.searchsorted(x_mm, x_lo)); ch = int(np.searchsorted(x_mm, x_hi))
    m = np.zeros_like(roi, dtype=bool)
    m[:, cl:ch] = True
    return m & roi


def _series(arr, mask):
    return np.nanmean(arr.reshape(arr.shape[0], -1)[:, mask.reshape(-1)], axis=1)


def main():
    d = np.load(CACHE_DIR / "stack.npz")
    meta = pd.read_csv(CACHE_DIR / "meta.csv")
    meta["timestamp"] = pd.to_datetime(meta["timestamp"])
    arrs = {"amplitude": d["amplitude"], "tof": d["tof"], "energy": d["energy"]}
    x_mm = d["x_mm"]; y_mm = d["y_mm"]; roi = d["roi_mask"]

    refs = {name: _xy_band(roi, x_mm, y_mm, *b) for name, b in REFS_X.items()}
    subregions = {name: _xband_in_roi(roi, x_mm, lo, hi) for name, (lo, hi) in SUBREGIONS.items()}

    # ---- per-plateau index lookup ----
    plateau_idx = {}
    plateau_time = {}
    for step in REST_STEPS:
        sel = meta[meta["step"] == step].sort_values("timestamp")
        plateau_idx[step] = sel.index.values
        plateau_time[step] = (sel["timestamp"] - sel["timestamp"].iloc[0]).dt.total_seconds().values / 60.0

    report = []
    report.append("# 35C charge-focus robustness diagnostics\n\n")
    report.append("Generated by `scripts/charge_focus/analyze_35c_robustness.py`.\n")
    report.append("Source cache: `_cache/stack.npz` + `_cache/meta.csv`.\n\n")
    report.append("Three tasks:\n"
                  "  A. Per-reference Delta-end (which refs drift, which is stable)\n"
                  "  B. mean-of-refs vs median-of-refs cell-specific Delta-end\n"
                  "  C. Tab-proximal / interior / tab-distal sub-ROI trajectories\n\n")

    # ====================================================================
    # TASK A: 4 reference regions individually
    # ====================================================================
    report.append("## Task A: individual reference regions (Delta vs rest start)\n\n")
    report.append("Sign convention: Delta(end) = ref-mean at end of rest minus ref-mean at start.\n")
    report.append("If common-mode is real, all 4 refs should move in the same direction with similar magnitudes.\n\n")

    taskA = {mod: [] for mod in ["amplitude", "tof", "energy"]}

    for mod in ["amplitude", "tof", "energy"]:
        unit, scale, sigma = UNITS[mod]
        fig, axes = plt.subplots(1, 4, figsize=(16, 4.2), constrained_layout=True, sharey=True)
        for col, (step, soc) in enumerate(zip(REST_STEPS, SOC_LABELS)):
            idx = plateau_idx[step]; t = plateau_time[step]
            ax = axes[col]
            roi_s = _series(arrs[mod][idx], roi) * scale
            d_roi = roi_s - roi_s[0]
            ax.plot(t, d_roi, "k-", lw=2.0, label="CELL ROI", zorder=5)

            row = {"SOC%": soc}
            ref_ends = []
            for ref_name in REFS_X:
                s = _series(arrs[mod][idx], refs[ref_name]) * scale
                d = s - s[0]
                ax.plot(t, d, "o-", lw=0.9, ms=3.5, label=ref_name, alpha=0.85)
                row[ref_name] = float(d[-1])
                ref_ends.append(d[-1])

            row["mean_ref"] = float(np.mean(ref_ends))
            row["median_ref"] = float(np.median(ref_ends))
            row["ref_std"] = float(np.std(ref_ends))
            row["sign_agree"] = bool(np.all(np.array(ref_ends) >= 0) or np.all(np.array(ref_ends) <= 0))
            row["cell_end"] = float(d_roi[-1])
            taskA[mod].append(row)

            ax.axhline(0, color="k", lw=0.4)
            ax.fill_between(t, -2*sigma, 2*sigma, color="gray", alpha=0.12, label="+/-2 sigma_ROI" if col==0 else None)
            ax.set_title(f"SOC {soc}% rest (step {step})", fontsize=10)
            ax.set_xlabel("rest time [min]")
            if col == 0:
                ax.set_ylabel(f"Delta{mod} vs t=0 [{unit}]")
            ax.grid(alpha=0.3)
            if col == 3:
                ax.legend(fontsize=7, loc="best")
        fig.suptitle(f"Task A: individual reference trajectories vs CELL ROI - {mod} "
                     f"(sigma_ROI = {sigma:.3g} {unit})", fontsize=11)
        fig.savefig(OUT_ROOT / f"taskA_individual_refs_{mod}.png", dpi=130)
        plt.close(fig)

    # Tables
    for mod in ["amplitude", "tof", "energy"]:
        unit, scale, sigma = UNITS[mod]
        report.append(f"### {mod}  (sigma_ROI = {sigma:.3g} {unit}; values in {unit})\n\n")
        report.append("| SOC | far-left | far-right | far-top | far-bot | CELL | mean_ref | median_ref | ref-std | sign-agree |\n")
        report.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---:|\n")
        for r in taskA[mod]:
            report.append(
                f"| {r['SOC%']}% | {r['far-left']:+.3g} | {r['far-right']:+.3g} | "
                f"{r['far-top']:+.3g} | {r['far-bot']:+.3g} | {r['cell_end']:+.3g} | "
                f"{r['mean_ref']:+.3g} | {r['median_ref']:+.3g} | {r['ref_std']:.3g} | "
                f"{'yes' if r['sign_agree'] else 'NO'} |\n"
            )
        # stability ranking by mean |Delta(end)| across plateaus
        ref_abs = {ref: float(np.mean([abs(r[ref]) for r in taskA[mod]])) for ref in REFS_X}
        ranking = sorted(ref_abs.items(), key=lambda kv: kv[1])
        report.append("\n_mean |Delta(end)| across 4 plateaus (lower = more stable):_  "
                      + ", ".join(f"**{n}** {v:.3g}" for n, v in ranking) + "\n\n")

    # ====================================================================
    # TASK B: mean vs median cell-specific Delta-end
    # ====================================================================
    report.append("## Task B: cell-specific Delta-end -- mean vs median over 4 refs\n\n")
    report.append("`cell_specific = (cell_end - cell_start) - (ref_aggregate_end - ref_aggregate_start)`\n")
    report.append("median is robust to a single bad reference; if median differs sharply from mean -> one ref is corrupting the result.\n\n")

    for mod in ["amplitude", "tof", "energy"]:
        unit, scale, sigma = UNITS[mod]
        report.append(f"### {mod}  (sigma_ROI = {sigma:.3g} {unit})\n\n")
        report.append("| SOC | cell raw end | mean-ref end | cell - mean end | (mean) z | median-ref end | cell - median end | (median) z |\n")
        report.append("|---:|---:|---:|---:|---:|---:|---:|---:|\n")
        for step, soc in zip(REST_STEPS, SOC_LABELS):
            idx = plateau_idx[step]
            cell = _series(arrs[mod][idx], roi) * scale
            d_cell = cell[-1] - cell[0]

            ref_series = []
            for ref_name in REFS_X:
                s = _series(arrs[mod][idx], refs[ref_name]) * scale
                ref_series.append(s)
            ref_series = np.array(ref_series)  # (4, n_t)

            ref_mean_d = float(np.mean(ref_series[:, -1] - ref_series[:, 0]))
            ref_median_d = float(np.median(ref_series[:, -1] - ref_series[:, 0]))

            d_spec_mean = d_cell - ref_mean_d
            d_spec_median = d_cell - ref_median_d

            report.append(
                f"| {soc}% | {d_cell:+.3g} | {ref_mean_d:+.3g} | {d_spec_mean:+.3g} | {d_spec_mean/sigma:+.1f} "
                f"| {ref_median_d:+.3g} | {d_spec_median:+.3g} | {d_spec_median/sigma:+.1f} |\n"
            )
        report.append("\n")

    # ====================================================================
    # TASK C: tab-vs-center sub-ROI trajectories
    # ====================================================================
    report.append("## Task C: tab-proximal vs interior vs tab-distal (no external reference)\n\n")
    report.append("X-bands intersected with the canonical 50x40 ROI:\n")
    for name, (lo, hi) in SUBREGIONS.items():
        n_px = int(subregions[name].sum())
        report.append(f"  - **{name}**: X in [{lo:.1f}, {hi:.1f}] mm -> {n_px} ROI pixels\n")
    report.append("\nBecause all three sub-regions are inside the same scan at the same time, "
                  "they share the same coupling-film state, the same TC08 reading, and the same system gain -- "
                  "so the difference between sub-regions is **immune to common-mode drift**, whether or not "
                  "the external reference regions behaved well.\n\n")

    taskC = {mod: [] for mod in ["amplitude", "tof", "energy"]}
    colors = {"tab-distal": "tab:blue", "interior": "tab:green", "tab-proximal": "tab:red"}

    for mod in ["amplitude", "tof", "energy"]:
        unit, scale, sigma = UNITS[mod]
        fig, axes = plt.subplots(1, 4, figsize=(16, 4.2), constrained_layout=True, sharey=True)
        for col, (step, soc) in enumerate(zip(REST_STEPS, SOC_LABELS)):
            idx = plateau_idx[step]; t = plateau_time[step]
            ax = axes[col]
            sub_series = {}
            for name in SUBREGIONS:
                s = _series(arrs[mod][idx], subregions[name]) * scale
                sub_series[name] = s
                d = s - s[0]
                ax.plot(t, d, "o-", color=colors[name], lw=1.3, ms=4, label=name)

            ax.axhline(0, color="k", lw=0.4)
            ax.fill_between(t, -2*sigma, 2*sigma, color="gray", alpha=0.15)
            ax.set_title(f"SOC {soc}% rest", fontsize=10)
            ax.set_xlabel("rest time [min]")
            ax.grid(alpha=0.3)
            if col == 0:
                ax.set_ylabel(f"Delta{mod} vs t=0 [{unit}]")
            if col == 3:
                ax.legend(fontsize=8, loc="best")

            # tab-proximal minus tab-distal series (the spatial-gradient signal)
            grad_series = (sub_series["tab-proximal"] - sub_series["tab-distal"])
            grad_d = grad_series - grad_series[0]
            taskC[mod].append({
                "SOC%": soc,
                "d_prox_end":    float(sub_series["tab-proximal"][-1] - sub_series["tab-proximal"][0]),
                "d_inter_end":   float(sub_series["interior"][-1] - sub_series["interior"][0]),
                "d_distal_end":  float(sub_series["tab-distal"][-1] - sub_series["tab-distal"][0]),
                "d_grad_end":    float(grad_d[-1]),
                "grad_rate_late_early": float(
                    np.mean(np.abs(np.diff(grad_series))[-3:]) /
                    max(np.mean(np.abs(np.diff(grad_series))[:3]), 1e-9)
                ),
            })
        fig.suptitle(f"Task C: tab-proximal / interior / tab-distal trajectories - {mod} "
                     f"(sigma_ROI = {sigma:.3g} {unit})", fontsize=11)
        fig.savefig(OUT_ROOT / f"taskC_tab_vs_center_{mod}.png", dpi=130)
        plt.close(fig)

    for mod in ["amplitude", "tof", "energy"]:
        unit, scale, sigma = UNITS[mod]
        report.append(f"### {mod}  (sigma_ROI = {sigma:.3g} {unit})\n\n")
        report.append("| SOC | Delta tab-prox end | Delta interior end | Delta tab-distal end | "
                      "(prox - distal) Delta | (prox - distal) z [sigma_ROI] | grad rate late/early |\n")
        report.append("|---:|---:|---:|---:|---:|---:|---:|\n")
        for r in taskC[mod]:
            report.append(
                f"| {r['SOC%']}% | {r['d_prox_end']:+.3g} | {r['d_inter_end']:+.3g} | "
                f"{r['d_distal_end']:+.3g} | {r['d_grad_end']:+.3g} | "
                f"{r['d_grad_end']/sigma:+.1f} | {r['grad_rate_late_early']:.2f} |\n"
            )
        report.append("\n_Interpretation: `(prox - distal) z` > 2 sigma means the spatial gradient grew during rest "
                      "in a way that is genuinely heterogeneous, not just system drift._\n\n")

    # Equilibrium across plateaus by sub-region (4 SOCs, 3 lines per modality)
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.2), constrained_layout=True)
    for ax, mod in zip(axes, ["amplitude", "tof", "energy"]):
        unit, scale, sigma = UNITS[mod]
        for name in SUBREGIONS:
            ends = []
            for step in REST_STEPS:
                idx = plateau_idx[step]
                ends.append(_series(arrs[mod][idx], subregions[name])[-1] * scale)
            ax.plot(SOC_LABELS, ends, "o-", color=colors[name], lw=1.4, ms=7, label=name)
        ax.set_xlabel("SOC [%]")
        ax.set_ylabel(f"end-of-rest mean {mod} [{unit}]")
        ax.set_title(f"{mod} equilibrium (sigma_ROI = {sigma:.2g})")
        ax.grid(alpha=0.3); ax.legend(fontsize=8)
    fig.suptitle("Task C: end-of-rest equilibrium per sub-region vs SOC", fontsize=11)
    fig.savefig(OUT_ROOT / "taskC_equilibrium_subregions.png", dpi=130)
    plt.close(fig)

    # ---- write report ----
    REPORT_PATH.write_text("".join(report), encoding="utf-8")
    print(f"wrote {REPORT_PATH}")
    for mod in ["amplitude", "tof", "energy"]:
        print(f"  taskA_individual_refs_{mod}.png")
        print(f"  taskC_tab_vs_center_{mod}.png")
    print(f"  taskC_equilibrium_subregions.png")


if __name__ == "__main__":
    main()
