"""Re-render all charge-focus static figures with Y-axis flipped so Y=0 sits
at the bottom (printer start = physical cell bottom side).

Monkey-patches matplotlib's Axes.imshow at module load: whenever it sees an
extent in the project's "inverted" form (extent[2] > extent[3]), it swaps
the third/fourth entries and sets origin='lower'. Net effect: data row 0
ends up at the bottom of the figure, axis labels run normally (small Y at
bottom, large Y at top), so plotted images match physical cell orientation.

Animation GIFs in 06_animation/ are NOT regenerated by this script (too slow).
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.axes
import numpy as np

_orig_imshow = matplotlib.axes.Axes.imshow


def _patched_imshow(self, X, *args, **kwargs):
    extent = kwargs.get("extent")
    if extent is not None and len(extent) == 4 and extent[2] > extent[3]:
        kwargs["extent"] = [extent[0], extent[1], extent[3], extent[2]]
        kwargs.setdefault("origin", "lower")
    return _orig_imshow(self, X, *args, **kwargs)


matplotlib.axes.Axes.imshow = _patched_imshow

HERE = Path(__file__).resolve().parent
PROJ = HERE.parents[1]
LONGRUN = PROJ / "scripts" / "longrun_analysis"
sys.path.insert(0, str(LONGRUN))

import common  # noqa: E402
from common import Stack  # noqa: E402

NEW_OUT = PROJ / "reports" / "longrun_cycling_22h_charge_focus"
common.OUT_ROOT = NEW_OUT
common.CACHE_PATH = NEW_OUT / "_cache" / "stack.npz"
common.META_PATH = NEW_OUT / "_cache" / "meta.csv"

_orig_load = common.load


def filtered_load(rebuild: bool = False) -> Stack:
    s = _orig_load(rebuild=False)
    keep = s.meta.step_tag.isin({"charge", "rest"}).values
    idx = np.where(keep)[0]
    new_meta = s.meta.iloc[idx].copy().reset_index(drop=True)
    soc_min = float(new_meta.soc_pct.min())
    new_meta["soc_pct"] = new_meta["soc_pct"] - soc_min
    return Stack(
        amplitude=s.amplitude[idx],
        tof=s.tof[idx],
        energy=s.energy[idx],
        x_mm=s.x_mm,
        y_mm=s.y_mm,
        roi_mask=s.roi_mask,
        meta=new_meta,
    )


common.load = filtered_load

import analysis_02_relaxation as A2  # noqa: E402
import analysis_03_beta_soc as A3  # noqa: E402
import analysis_04_pca as A4  # noqa: E402
import analysis_05_reversibility as A5  # noqa: E402

sys.path.insert(0, str(HERE))
import analysis_07_tab_heterogeneity as A7  # noqa: E402
import analysis_08_rest_gradient_decay as A8  # noqa: E402


def main():
    only = set(sys.argv[1:]) or None
    steps = [
        ("02_relaxation", A2),
        ("03_beta_soc", A3),
        ("04_pca", A4),
        ("05_equilibrium", A5),
        ("07_tab_heterogeneity", A7),
        ("08_rest_gradient_decay", A8),
    ]
    for name, mod in steps:
        if only and not any(o in name for o in only):
            continue
        print(f"\n=== {name} ===")
        mod.main()
    print("\nAll static figures re-rendered with Y-flip. (06_animation GIFs not regenerated.)")


if __name__ == "__main__":
    main()
